spring:
  application:
    name: gfeed
    
  datasource:
    url: jdbc:mysql://localhost:3306/social
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
   port: 9020
