spring:
  application:
    name: zuul

server:
  port: 9999
  

zuul:
  routes: 
        profiles:
          path: /profiles/**
          url: http://localhost:9999/profiles/
          service-id: social
          strip-prefix: true
#     movies:
# #      url: http://localhost8080/
#       path: /social
#       service-id: social
#       strip-prefix: true
     
