spring:
  application:
    name: zuul

server:
  port: 9999
  

zuul:
  routes: 
#     movies:
# #      url: http://localhost8080/
#       path: /social
#       service-id: social
#       strip-prefix: true
      profiles:
         path: /profiles
         service-id: social
         strip-prefix: true
