spring:
  application:
    name: zuul

server:
  port: 9999
  

zuul:
  routes: 
        profile-server:
          path: /profiles/**
#           url: http://localhost:9001/profiles/
          service-id: profile
          strip-prefix: true
#     movies:
# #      url: http://localhost8080/
#       path: /social
#       service-id: social
#       strip-prefix: true
     
